In [1]:
from sklearn.linear_model import LinearRegression

In [2]:
model = LinearRegression(normalize=True)
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)


In [3]:
import numpy as np

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x,y = np.arange(10).reshape((5,2)), range(5)

In [7]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
list(y)

[0, 1, 2, 3, 4]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [10]:
X_train

array([[8, 9],
       [6, 7],
       [0, 1]])

In [11]:
X_test

array([[2, 3],
       [4, 5]])

In [12]:
y_train

[4, 3, 0]

In [13]:
y_test

[1, 2]

In [14]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [15]:
predictions = model.predict(X_test)

In [16]:
predictions

array([1., 2.])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [25]:
predictions

array([[1.],
       [2.]])